// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD35It2hv4JljTPgp4xL_28MiJBPpND-f8',
    appId: '1:950225253942:web:90413be011fed0dd0dca97',
    messagingSenderId: '950225253942',
    projectId: 'flick-79e97',
    authDomain: 'flick-79e97.firebaseapp.com',
    storageBucket: 'flick-79e97.appspot.com',
    measurementId: 'G-BFDZB8DWK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn9UFgD_rw31s_LXqS0QA5-VsOGqwGcNU',
    appId: '1:950225253942:android:03b71cc71512ac320dca97',
    messagingSenderId: '950225253942',
    projectId: 'flick-79e97',
    storageBucket: 'flick-79e97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr5_rK5lLw4FBY9Ew_5B-TmtVkjMWPLBk',
    appId: '1:950225253942:ios:178c8ebda42eef210dca97',
    messagingSenderId: '950225253942',
    projectId: 'flick-79e97',
    storageBucket: 'flick-79e97.appspot.com',
    iosBundleId: 'com.example.flick',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr5_rK5lLw4FBY9Ew_5B-TmtVkjMWPLBk',
    appId: '1:950225253942:ios:c056c99267cbc1b90dca97',
    messagingSenderId: '950225253942',
    projectId: 'flick-79e97',
    storageBucket: 'flick-79e97.appspot.com',
    iosBundleId: 'com.example.flick.RunnerTests',
  );
}
