import 'package:get/get_navigation/src/root/internacionalization.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'ar_SA': {
          // "Get Rid of Paper cards": "التخلص من البطاقات الورقية",
          // "Custom Messages will be shown here": "سيتم عرض الرسائل المخصصة هنا",
          // "Create an Account": "إنشاء حساب",
          // "Already have an Account? Sign in": "هل لديك حساب؟ تسجيل الدخول",
          // "Login": "تسجيل الدخول",
          // "Add your Login details below": "أضف تفاصيل تسجيل الدخول أدناه",
          // "Email": "البريد الإلكتروني",
          // "Password": "كلمة المرور",
          // "Forgot Password?": "هل نسيت كلمة المرور؟",
          // "Login with Phone Number": "تسجيل الدخول برقم الهاتف",
          // "Or Login in as": "أو تسجيل الدخول كـ",
          // "Login with Mobile Number": "تسجيل الدخول برقم الهاتف المحمول",
          // "Enter your Registered Mobile Number Below":
          //     "أدخل رقم هاتفك المحمول المسجل أدناه",
          // "Login with Email": "تسجيل الدخول بالبريد الإلكتروني",
          // "Verification Code": "رمز التحقق",
          // "Enter 6 digit code sent to your registered mobile number":
          //     "أدخل رمزًا مكونًا من 6 أرقام تم إرساله إلى رقم هاتفك المحمول المسجل",
          // "Verify": "تحقق",
          // "Signup": "التسجيل",
          // "Add your Signup details below": "أضف تفاصيل التسجيل أدناه",
          // "Email can not be empty": "لا يمكن ترك حقل البريد الإلكتروني فارغًا",
          // "Password can not be empty": "لا يمكن ترك حقل كلمة المرور فارغًا",
          // "Password should not include spaces":
          //     "يجب ألا تحتوي كلمة المرور على مسافات",
          // "Repeat Password": "تكرار كلمة المرور",
          // "Signup with Mobile Number": "التسجيل برقم الهاتف المحمول",
          // "Or Signup as": "أو قم بالتسجيل باسم",
          // "Enter your Signup details Below": "أدخل تفاصيل التسجيل أدناه",
          // "Please write valid number": "يرجى كتابة رقم صحيح",
          // "write valid code": "يرجى كتابة رمز صحيح",
          // "Loading...": "جار التحميل...",
          // "Add Details": "إضافة التفاصيل",
          // "Please enter your Information below": "يرجى إدخال معلوماتك أدناه",
          // "This will be shown on your flick profile":
          //     "سيظهر هذا على ملفك الشخصي في flick",
          // "Name can not be empty": "لا يمكن ترك حقل الاسم فارغًا",
          // "Name": "الاسم",
          // "Profession": "المهنة",
          // "Organization": "المؤسسة",
          // "Save": "حفظ",
          // "Forgot Password": "نسيت كلمة المرور",
          // "Please enter your registered email id below":
          //     "يرجى إدخال معرّف البريد الإلكتروني المسجل أدناه",
          // "Please write valid email": "يرجى كتابة بريد إلكتروني صحيح",
          // "Add @ character please": "يرجى إضافة علامة @ من فضلك",
          // "Send Verification Link": "إرسال رابط التحقق",
          // "Please enter your registered Mobile Number below":
          //     "يرجى إدخال رقم الهاتف المحمول المسجل أدناه",
          // "Please enter your new password below":
          //     "يرجى إدخال كلمة المرور الجديدة أدناه",
          // "Enter new Password": "أدخل كلمة المرور الجديدة",
          // "please do not use spaces": "يرجى عدم استخدام المسافات",
          // "Repeat new Password": "تكرار كلمة المرور الجديدة",
          // "Reset Password": "إعادة تعيين كلمة المرور",
          // "Please wait...": "يرجى الانتظار...",
          // "Password changed successfully": "تم تغيير كلمة المرور بنجاح",
          // "go to Login": "الانتقال إلى تسجيل الدخول",
          // "Profile": "الملف الشخصي",
          // "Add Links": "إضافة الروابط",
          // "Share": "مشاركة",
          // "Settings": "الإعدادات",
          // "Demo Name": "اسم التجربة",
          // "Demo Profession": "مهنة التجربة",
          // "Demo Organization": "مؤسسة التجربة",
          // "Preview": "معاينة",
          // "Direct": "مباشر",
          // "Private": "خاص",
          // "No link is added": "لم يتم إضافة رابط",
          // "Add new Links": "إضافة روابط جديدة",
          // "Link Title": "عنوان الرابط",
          // "format should be www": "يجب أن يكون التنسيق www",
          // "Username": "اسم المستخدم",
          // "this field is required": "هذا الحقل مطلوب",
          // "Choose Category": "اختر الفئة",
          // "Please choose category for this application.\nnot choosing any category will make this handle as public\nautomatically":
          //     "يرجى اختيار الفئة لهذا التطبيق.\nعدم اختيار أي فئة سيجعل هذا المعالج عامًا\nتلقائيًا",
          // "Business": "أعمال",
          // "Public": "عام",
          // "Social media link updated successfully":
          //     "تم تحديث رابط وسائل التواصل الاجتماعي بنجاح",
          // "Social media link could not be updated":
          //     "تعذر تحديث رابط وسائل التواصل الاجتماعي",
          // "Continue": "متابعة",
          // "Social media link deleted successfully":
          //     "تم حذف رابط وسائل التواصل الاجتماعي بنجاح",
          // "Social media link could not be deleted":
          //     "تعذر حذف رابط وسائل التواصل الاجتماعي",
          // "Delete": "حذف",
          // "Cancel": "إلغاء",
          // "Your account has been private": "تم تحديث حالة حسابك إلى خاص",
          // "Your account has been public": "تم تحديث حالة حسابك إلى عام",
          // "There was an issue Please try again":
          //     "حدثت مشكلة، يرجى المحاولة مرة أخرى",
          // "Edit Profile": "تعديل الملف الشخصي",
          // "Phone": "الهاتف",
          // "Update": "تحديث",
          // "Enter Flick Code": "أدخل رمز الفليك",
          // "Flick code is provided to you in product Package":
          //     "تم توفير رمز الفليك لك في حزمة المنتج",
          // "Flick Code": "رمز الفليك",
          // "Change Language": "تغيير اللغة",
          // "English": "الإنجليزية",
          // "Arabic": "العربية",
          // "Activate Flick": "تفعيل الفليك",
          // "Activate your Flick product": "تفعيل منتج الفليك الخاص بك",
          // "Change Password": "تغيير كلمة المرور",
          // "Change your password": "تغيير كلمة المرور الخاصة بك",
          // "Private Mode": "الوضع الخاص",
          // "Share only handles marked in private category":
          //     "مشاركة الحسابات المحددة في الفئة الخاصة فقط",
          // "Share by Category": "مشاركة حسابات حسب الفئة",
          // "Share profile upon category selection":
          //     "مشاركة الملف الشخصي عند اختيار الفئة",
          // "Share QR": "مشاركة رمز الاستجابة السريعة",
          // "Share QR to access your public profile":
          //     "مشاركة رمز الاستجابة السريعة للوصول إلى ملفك الشخصي العام",
          // "Dark Mode": "الوضع الداكن",
          // "View App in Dark Mode": "عرض التطبيق في الوضع الداكن",
          // "Language": "اللغة",
          // "Change language": "تغيير اللغة",
          // "Lost Mode": "وضع الفقدان",
          // "Disable your tag • Add Custom Message":
          //     "تعطيل علامتك • إضافة رسالة مخصصة",
          // "Logout": "تسجيل الخروج",
          // "Deactivate Account": "إلغاء تنشيط الحساب",
          // "Download Qr": "تحميل رمز الاستجابة السريعة",
          // "Share by Whatsapp": "مشاركة عبر الواتساب",
          // "Share by Instagram": "مشاركة عبر إنستجرام",
          // "Share by Gmail": "مشاركة عبر بريد جوجل",
          // "Share by Text": "مشاركة عبر النص",
          // "Share by Other": "مشاركة عبر وسائل أخرى",
          // "Applications": "التطبيقات",
          // "Search": "البحث",
          // "Contact Info": "معلومات الاتصال",
          // "Social Media": "وسائل التواصل الاجتماعي",
          // "Instagram": "إنستجرام",
          // "LinkedIn": "لينكدإن",
          // "Line": "لاين",
          // "Reddit": "ريديت",
          // "Facebook": "فيسبوك",
          // "WhatsApp": "واتساب",
          // "Meet Me": "تعرف علي",
          // "YouTube": "يوتيوب",
          // "X": "إكس",
          // "TikTok": "تيك توك",
          // "Tumblr": "تمبلر",
          // "Social media link added successfully":
          //     "تمت إضافة رابط وسائل التواصل الاجتماعي بنجاح",
          // "Social media link could not be added":
          //     "تعذرت إضافة رابط وسائل التواصل الاجتماعي",
          // "Payments": "المدفوعات",
          // "Music": "الموسيقى",
          // "Other": "أخرى",
          // //////
          // "Call": "اتصال",
          // "Number": "الرقم",
          // "Wechat": "ويتشات",
          // "User Name": "اسم المستخدم",
          // "Contact Card": "بطاقة الاتصال",
          // "Address": "العنوان",
          // "Title": "العنوان",
          // "Link": "الرابط",
          // "Face Time": "فيس تايم",
          // "Email Title": "عنوان البريد الإلكتروني",
          // "Email ID": "البريد الإلكتروني",
          // "Viber": "فايبر",
          // "Viber Number": "رقم فايبر",
          // "Messages": "الرسائل",
          // "Text": "النص",
          // "title": "العنوان",
          // "Instagram Username": "اسم المستخدم في إنستجرام",
          // "linkedin Username": "اسم المستخدم في لينكدإن",
          // "Line Username": "اسم المستخدم في لاين",
          // "Reddit Username": "اسم المستخدم في ريديت",
          // "facebook Username": "اسم المستخدم في فيسبوك",
          // "Snapchat": "سناب شات",
          // "Snapchat Username": "اسم المستخدم في سناب شات",
          // "WhatsApp Username": "اسم المستخدم في واتساب",
          // "Meetme": "ميتمي",
          // "Meetme Username": "اسم المستخدم في ميتمي",
          // "Youtube": "يوتيوب",
          // "YouTube Username": "اسم المستخدم في يوتيوب",
          // "Twitter": "تويتر",
          // "Twitter Username": "اسم المستخدم في تويتر",
          // "TikTok Username": "اسم المستخدم في تيك توك",
          // "Tumblr Username": "اسم المستخدم في تمبلر",
          // "BenefitPay": "بنفت باي",
          // "Link url": "رابط الرابط",
          // "Paypal": "باي بال",
          // "Apple Music": "آبل ميوزك",
          // "Spotify": "سبوتيفاي",
          // "SoundCloud": "ساوند كلاود",
          // "Microsoft Teams": "مايكروسوفت تيمز",
          // "Podcast": "بودكاست",
          // "Zoom Meeting": "اجتماع زووم",
          // 'Website': 'موقع الويب',
          // 'Play Store': 'متجر بلاي',
          // 'Food Menu': 'قائمة الطعام',
          // 'Google Review': 'تقييم جوجل',
          // 'Huawei App': 'تطبيق هواوي',
          // 'IOS App': 'تطبيق iOS',
          // 'Tripadvisor': 'تريب أدفايزر',
          // 'url': 'الرابط',
          // 'App Name Title': 'عنوان اسم التطبيق',
          // 'App Name': 'اسم التطبيق',
          // 'Application Name': 'اسم التطبيق',
          // 'Website url': 'رابط الموقع',
          // 'Play Store url': 'رابط متجر بلاي',
          // 'Food Menu url': 'رابط قائمة الطعام',
          // 'Google Review url': 'رابط تقييم جوجل',
          // 'Huawei App url': 'رابط تطبيق هواوي',
          // 'IOS App url': 'رابط تطبيق iOS',
          // 'Tripadvisor url': 'رابط تريب أدفايزر',
          // 'Current Password': 'كلمة المرور الحالية',
          // 'New Password': 'كلمة المرور الجديدة',
          // 'Update Password': 'تحديث كلمة المرور',
          // 'Deactivate Flick': 'إلغاء تنشيط الفليك',
          // 'this will make your profile hidden and your flick will not be accessible by anyone':
          //     'سيجعل هذا ملفك الشخصي مخفيًا ولا يمكن الوصول إلى الفليك الخاص بك من قبل أي شخص',
          // 'Custom Message': 'رسالة مخصصة',
          // 'Add your Customer Message here': 'أضف رسالتك المخصصة هنا',
          // 'Are you sure you want to Logout?':
          //     'هل أنت متأكد أنك تريد تسجيل الخروج؟',
          // 'Are you sure you want to Exit?': 'هل أنت متأكد أنك تريد الخروج؟',
          // 'No': 'لا',
          // 'Yes': 'لا',
          // 'Exit': 'الخروج',
          ///////////
          "Get Rid of Paper cards": "التخلص من البطاقات الورقية",
          "Custom Messages will be shown here": "سيتم عرض الرسائل المخصصة هنا",
          "Create an Account": "إنشاء حساب",
          "Already have an Account? Sign in": "هل لديك حساب؟ تسجيل الدخول",
          "Login": "تسجيل الدخول",
          "Add your Login details below": "أضف تفاصيل تسجيل الدخول أدناه",
          "Email": "البريد الإلكتروني",
          "Password": "كلمة المرور",
          "Forgot Password?": "هل نسيت كلمة المرور؟",
          "Login with Phone Number": "تسجيل الدخول برقم الهاتف",
          "Or Login in as": "أو تسجيل الدخول عبر",
          "Login with Mobile Number": "تسجيل الدخول برقم الهاتف ",
          "Enter your Registered Mobile Number Below":
              "أدخل رقم هاتفك المسجل أدناه",
          "Login with Email": "تسجيل الدخول بالبريد الإلكتروني",
          "Verification Code": "رمز التحقق",
          "Enter 6 digit code sent to your registered mobile number":
              "أدخل رمزًا مكونًا من 6 أرقام تم إرساله إلى رقم هاتفك المسجل",
          "Verify": "تحقق",
          "Signup": "التسجيل",
          "Add your Signup details below": "أضف تفاصيل التسجيل أدناه",
          "Email can not be empty": "لا يمكن ترك حقل البريد الإلكتروني فارغًا",
          "Password can not be empty": "لا يمكن ترك حقل كلمة المرور فارغًا",
          "Password should not include spaces":
              "يجب ألا تحتوي كلمة المرور على مسافات",
          "Repeat Password": "تأكيد كلمة المرور",
          "Signup with Mobile Number": "التسجيل برقم الهاتف ",
          "Or Signup as": "أو قم بإنشاء حساب عن طريق",
          "Enter your Signup details Below": "أدخل تفاصيل التسجيل أدناه",
          "Please write valid number": "يرجى كتابة رقم هاتف صحيح",
          "write valid code": "يرجى كتابة رمز صحيح",
          "Loading...": "جار التحميل...",
          "Add Details": "إضافة التفاصيل",
          "Please enter your Information below": "يرجى إدخال معلوماتك أدناه",
          "This will be shown on your flick profile":
              "سيظهر هذا على ملفك الشخصي في flick",
          "Name can not be empty": "لا يمكن ترك حقل الاسم فارغًا",
          "Name": "الاسم",
          "Profession": "المهنة",
          "Organization": "المؤسسة",
          "Save": "حفظ",
          "Forgot Password": "نسيت كلمة المرور",
          "Please enter your registered email id below":
              "يرجى إدخال البريد الإلكتروني المسجل أدناه",
          "Please write valid email": "يرجى كتابة بريد إلكتروني صحيح",
          "Add @ character please": "يرجى إضافة علامة @ من فضلك",
          "Send Verification Link": "إرسال رابط التحقق",
          "Please enter your registered Mobile Number below":
              "يرجى إدخال رقم الهاتف المسجل أدناه",
          "Please enter your new password below":
              "يرجى إدخال كلمة المرور الجديدة أدناه",
          "Enter new Password": "أدخل كلمة المرور الجديدة",
          "please do not use spaces": "يرجى عدم استخدام المسافات",
          "Repeat new Password": "تأكيد كلمة المرور الجديدة",
          "Reset Password": "إعادة تعيين كلمة المرور",
          "Please wait...": "يرجى الانتظار...",
          "Password changed successfully": "تم تغيير كلمة المرور بنجاح",
          "go to Login": "الانتقال إلى تسجيل الدخول",
          "Profile": "الملف الشخصي",
          "Add Links": "إضافة الروابط",
          "Share": "مشاركة",
          "Settings": "الإعدادات",
          "Demo Name": "اسم التجربة",
          "Demo Profession": "مهنة التجربة",
          "Demo Organization": "مؤسسة التجربة",
          "Preview": "معاينة",
          "Direct": "مباشر",
          "Private": "خاص",
          "No link is added": "لم يتم إضافة رابط",
          "Add new Links": "إضافة روابط جديدة",
          "Link Title": "عنوان الرابط",
          "format should be www": "يجب أن يكون التنسيق www",
          "Username": "اسم المستخدم",
          "this field is required": "هذا الحقل مطلوب",
          "Choose Category": "اختر الفئة",
          "Please choose category for this application.\nnot choosing any category will make this handle as public\nautomatically":
              "يرجى اختيار الفئة لهذا التطبيق.\nعدم اختيار أي فئة سيجعل هذا المعالج عامًا\nتلقائيًا",
          "Business": "أعمال",
          "Public": "عام",
          "Social media link updated successfully":
              "تم تحديث رابط وسائل التواصل الاجتماعي بنجاح",
          "Social media link could not be updated":
              "تعذر تحديث رابط وسائل التواصل الاجتماعي",
          "Continue": "متابعة",
          "Social media link deleted successfully":
              "تم حذف رابط وسائل التواصل الاجتماعي بنجاح",
          "Social media link could not be deleted":
              "تعذر حذف رابط وسائل التواصل الاجتماعي",
          "Delete": "حذف",
          "Cancel": "إلغاء",
          "Your account has been private": "تم تحديث حالة حسابك إلى خاص",
          "Your account has been public": "تم تحديث حالة حسابك إلى عام",
          "There was an issue Please try again":
              "حدثت مشكلة، يرجى المحاولة مرة أخرى",
          "Edit Profile": "تعديل الملف الشخصي",
          "Phone": "الهاتف",
          "Update": "تحديث",
          "Enter Flick Code": " أدخل رمز Flick",
          "Flick code is provided to you in product Package":
              "تم توفير رمز الفليك لك في حزمة المنتج",
          "Flick Code": " رمز Flick",
          "Change Language": "تغيير اللغة",
          "English": "الإنجليزية",
          "Arabic": "العربية",
          "Activate Flick": " تفعيل Flick",
          "Activate your Flick product": "تفعيل منتج الفليك الخاص بك",
          "Change Password": "تغيير كلمة المرور",
          "Change your password": "تغيير كلمة المرور الخاصة بك",
          "Private Mode": "الوضع الخاص",
          "Share only handles marked in private category":
              "مشاركة الحسابات المحددة في الفئة الخاصة فقط",
          "Share by Category": "مشاركة الحسابات حسب الفئة",
          "Share profile upon category selection":
              "مشاركة الملف الشخصي عند اختيار الفئة",
          "Share QR": "مشاركة رمز الاستجابة السريعة",
          "Share QR to access your public profile":
              "مشاركة رمز الاستجابة السريعة للوصول إلى ملفك الشخصي العام",
          "Dark Mode": "الوضع الداكن",
          "View App in Dark Mode": "عرض التطبيق في الوضع الداكن",
          "Language": "اللغة",
          "Change language": "تغيير اللغة",
          "Lost Mode": "وضع الفقدان",
          "Disable your tag • Add Custom Message":
              "تعطيل علامتك • إضافة رسالة مخصصة",
          "Logout": "تسجيل الخروج",
          "Deactivate Account": "إلغاء تنشيط الحساب",
          "Download Qr": "تحميل رمز الاستجابة السريعة",
          "Share by Whatsapp": "مشاركة عبر الواتساب",
          "Share by Instagram": "مشاركة عبر إنستجرام",
          "Share by Gmail": "مشاركة عبر بريد جوجل",
          "Share by Text": "مشاركة عبر النص",
          "Share by Other": "مشاركة عبر وسائل أخرى",
          "Applications": "التطبيقات",
          "Search": "البحث",
          "Contact Info": "معلومات الاتصال",
          "Social Media": "وسائل التواصل الاجتماعي",
          "Instagram": "إنستجرام",
          "LinkedIn": "لينكدإن",
          "Line": "لاين",
          "Reddit": "ريديت",
          "Facebook": "فيسبوك",
          "WhatsApp": "واتساب",
          "Meet Me": "ميت مي",
          "YouTube": "يوتيوب",
          "X": "إكس",
          "TikTok": "تيك توك",
          "Tumblr": "تمبلر",
          "Social media link added successfully":
              "تمت إضافة رابط وسائل التواصل الاجتماعي بنجاح",
          "Social media link could not be added":
              "تعذر إضافة رابط وسائل التواصل الاجتماعي",
          "Payments": "المدفوعات",
          "Music": "الموسيقى",
          "Other": "أخرى",
          //////
          "Call": "اتصال",
          "Number": "الرقم",
          "Wechat": "وي شات",
          "User Name": "اسم المستخدم",
          "Contact Card": "بطاقة الاتصال",
          "Address": "العنوان",
          "Title": "العنوان",
          "Link": "الرابط",
          "Face Time": "فيس تايم",
          "Email Title": "عنوان البريد الإلكتروني",
          "Email ID": "البريد الإلكتروني",
          "Viber": "فايبر",
          "Viber Number": "رقم فايبر",
          "Messages": "الرسائل",
          "Text": "النص",
          "title": "العنوان",
          "Instagram Username": "اسم المستخدم في إنستجرام",
          "linkedin Username": "اسم المستخدم في لينكدإن",
          "Line Username": "اسم المستخدم في لاين",
          "Reddit Username": "اسم المستخدم في ريديت",
          "facebook Username": "اسم المستخدم في فيسبوك",
          "Snapchat": "سناب شات",
          "Snapchat Username": "اسم المستخدم في سناب شات",
          "WhatsApp Username": "اسم المستخدم في واتساب",
          "Meetme": "ميت مي",
          "Meetme Username": "اسم المستخدم في ميت مي",
          "Youtube": "يوتيوب",
          "YouTube Username": "اسم المستخدم في يوتيوب",
          "Twitter": "تويتر",
          "Twitter Username": "اسم المستخدم في تويتر",
          "TikTok Username": "اسم المستخدم في تيك توك",
          "Tumblr Username": "اسم المستخدم في تمبلر",
          "BenefitPay": "بنفت باي",
          "Link url": "رابط الرابط",
          "Paypal": "باي بال",
          "Apple Music": "آبل ميوزك",
          "Spotify": "سبوتيفاي",
          "SoundCloud": "ساوند كلاود",
          "Microsoft Teams": "مايكروسوفت تيمز",
          "Podcast": "بودكاست",
          "Zoom Meeting": "اجتماع زووم",
          'Website': 'موقع الويب',
          'Play Store': 'متجر بلاي',
          'Food Menu': 'قائمة الطعام',
          'Google Review': 'تقييم جوجل',
          'Huawei App': 'تطبيق هواوي',
          'IOS App': 'تطبيق iOS',
          'Tripadvisor': 'تريب أدفايزر',
          'url': 'الرابط',
          'App Name Title': 'عنوان اسم التطبيق',
          'App Name': 'اسم التطبيق',
          'Application Name': 'اسم التطبيق',
          'Website url': 'رابط الموقع',
          'Play Store url': 'رابط متجر بلاي',
          'Food Menu url': 'رابط قائمة الطعام',
          'Google Review url': 'رابط تقييم جوجل',
          'Huawei App url': 'رابط تطبيق هواوي',
          'IOS App url': 'رابط تطبيق iOS',
          'Tripadvisor url': 'رابط تريب أدفايزر',
          'Current Password': 'كلمة المرور الحالية',
          'New Password': 'كلمة المرور الجديدة',
          'Update Password': 'تحديث كلمة المرور',
          'Deactivate Flick': ' Flick إلغاء تنشيط ',
          'this will make your profile hidden and your flick will not be accessible by anyone':
              'سيجعل هذا ملفك الشخصي مخفيًا ولا يمكن الوصول إلى الحساب الخاص بك من قبل أي شخص',
          'Custom Message': 'رسالة مخصصة',
          'Add your Customer Message here': 'أضف رسالتك المخصصة هنا',
          'Are you sure you want to Logout?':
              'هل أنت متأكد أنك تريد تسجيل الخروج؟',
          'Are you sure you want to Exit?': 'هل أنت متأكد أنك تريد الخروج؟',
          'No': 'لا',
          'Yes': 'نعم',
          'Exit': 'الخروج',
          'FAQ': 'الأسئلة الشائعة',
        },
        ///////////////////////////////////////////////////////////////////////////////////////////////////
        'en_US': {
          'Get Rid of Paper cards': 'Get Rid of Paper cards',
          'Custom Messages will be shown here':
              'Custom Messages will be shown here',
          'Create an Account': 'Create an Account',
          'Already have an Account? Sign in':
              'Already have an Account? Sign in',
          'Login': 'Login',
          'Add your Login details below': 'Add your Login details below',
          'Email': 'Email',
          'Password': 'Password',
          'Forgot Password?': 'Forgot Password?',
          'Login with Phone Number': 'Login with Phone Number',
          'Or Login in as': 'Or Login in as',
          'Login with Mobile Number': 'Login with Mobile Number',
          'Enter your Registered Mobile Number Below':
              'Enter your Registered Mobile Number Below',
          'Login with Email': 'Login with Email',
          'Verification Code': 'Verification Code',
          'Enter 6 digit code sent to your registered mobile number':
              'Enter 6 digit code sent to your registered mobile number',
          'Verify': 'Verify',
          'Signup': 'Signup',
          'Add your Signup details below': 'Add your Signup details below',
          'Email can not be empty': 'Email can not be empty',
          'Password can not be empty': 'Password can not be empty',
          'Password should not include spaces':
              'Password should not include spaces',
          'Repeat Password': 'Repeat Password',
          'Signup with Mobile Number': 'Signup with Mobile Number',
          'Or Signup as"': 'Or Signup as"',
          'Enter your Signup details Below': 'Enter your Signup details Below',
          'Please write valid number': 'Please write valid number',
          'write valid code': 'write valid code',
          'Loading...': 'Loading...',
          'Add Details': 'Add Details',
          'Please enter your Information below':
              'Please enter your Information below',
          'This will be shown on your flick profile':
              'This will be shown on your flick profile',
          'Name can not be empty': 'Name can not be empty',
          'Name': 'Name',
          'Profession': 'Profession',
          'Organization': 'Organization',
          'Save': 'Save',
          'Forgot Password': 'Forgot Password',
          'Please enter your registered email id below':
              'Please enter your registered email id below',
          'Please write valid email': 'Please write valid email',
          'Add @ character please': 'Add @ character please',
          'Send Verification Link': 'Send Verification Link',
          'Please enter your registered Mobile Number below':
              'Please enter your registered Mobile Number below',
          'Please enter your new password below':
              'Please enter your new password below',
          'Enter new Password': 'Enter new Password',
          'please do not use spaces': 'please do not use spaces',
          'Repeat new Password': 'Repeat new Password',
          'Reset Password': 'Reset Password',
          'Please wait...': 'Please wait...',
          'Password changed successfully': 'Password changed successfully',
          'go to Login': 'go to Login',
          'Profile': 'Profile',
          'Add Links': 'Add Links',
          'Share': 'Share',
          'Settings': 'Settings',
          'Demo Name': 'Demo Name',
          'Demo Profession': 'Demo Profession',
          'Demo Organization': 'Demo Organization',
          'Preview': 'Preview',
          'Direct': 'Direct',
          'Private': 'Private',
          'No link is added': 'No link is added',
          'Add new Links': 'Add new Links',
          'Link Title': 'Link Title',
          'format should be www': 'format should be www',
          'Username': 'Username',
          'this field is required': 'this field is required',
          'Choose Category': 'Choose Category',
          'Please choose category for this application.\nnot choosing any category will make this handle as public\nautomatically':
              'Please choose category for this application.\nnot choosing any category will make this handle as public\nautomatically',
          'Business': 'Business',
          'Public': 'Public',
          'Social media link updated successfully':
              'Social media link updated successfully',
          'Social media link could not be updated':
              'Social media link could not be updated',
          'Continue': 'Continue',
          'Social media link deleted successfully':
              'Social media link deleted successfully',
          'Social media link could not be deleted':
              'Social media link could not be deleted',
          'Delete': 'Delete',
          'Cancel': 'Cancel',
          'Your account has been private': 'Your account has been private',
          'Your account has been public': 'Your account has been public',
          'There was an issue Please try again':
              'There was an issue Please try again',
          'Edit Profile': 'Edit Profile',
          'Phone': 'Phone',
          'Update': 'Update',
          'Enter Flick Code': 'Enter Flick Code',
          'Flick code is provided to you in product Package':
              'Flick code is provided to you in product Package',
          'Flick Code': 'Flick Code',
          'Change Language': 'Change Language',
          'English': 'English',
          'Arabic': 'Arabic',
          'Activate Flick': 'Activate Flick',
          'Activate your Flick product': 'Activate your Flick product',
          'Change Password': 'Change Password',
          'Change your password': 'Change your password',
          'Private Mode': 'Private Mode',
          'Share only handles marked in private category':
              'Share only handles marked in private category',
          'Share by Category': 'Share by Category',
          'Share profile upon category selection':
              'Share profile upon category selection',
          'Share QR': 'Share QR',
          'Share QR to access your public profile':
              'Share QR to access your public profile',
          'Dark Mode': 'Dark Mode',
          'View App in Dark Mode': 'View App in Dark Mode',
          'Language': 'Language',
          'Change language': 'Change language',
          'Lost Mode': 'Lost Mode',
          'Disable your tag • Add Custom Message':
              'Disable your tag • Add Custom Message',
          'Logout': 'Logout',
          'Deactivate Account': 'Deactivate Account',
          'Download Qr': 'Download Qr',
          'Share by Whatsapp': 'Share by Whatsapp',
          'Share by Instagram': 'Share by Instagram',
          'Share by Gmail': 'Share by Gmail',
          'Share by Text': 'Share by Text',
          'Share by Other': 'Share by Other',
          'Applications': 'Applications',
          'Search': 'Search',
          'Contact Info': 'Contact Info',
          'Social Media': 'Social Media',
          'Instagram': 'Instagram',
          'LinkedIn': 'LinkedIn',
          'Line': 'Line',
          'Reddit': 'Reddit',
          'Facebook': 'Facebook',
          'WhatsApp': 'WhatsApp',
          'Meet Me': 'Meet Me',
          'YouTube': 'YouTube',
          'X': 'X',
          'TikTok': 'TikTok',
          'Tumblr': 'Tumblr',
          'Social media link added successfully':
              'Social media link added successfully',
          'Social media link could not be added':
              'Social media link could not be added',
          'Payments': 'Payments',
          'Music': 'Music',
          'Other': 'Other',
////////
          "Call": "Call",
          "Number": "Number",
          "Wechat": "Wechat",
          "User Name": "User Name",
          "Contact Card": "Contact Card",
          "Address": "Address",
          "Title": "Title",
          "Link": "Link",
          "Face Time": "Face Time",
          "Email Title": "Email Title",
          "Email ID": "Email ID",
          "Viber": "Viber",
          "Viber Number": "Viber Number",
          "Messages": "Messages",
          "Text": "Text",
          "title": "Title",
          "Instagram Username": "Instagram Username",
          "linkedin Username": "LinkedIn Username",
          "Line Username": "Line Username",
          "Reddit Username": "Reddit Username",
          "facebook Username": "Facebook Username",
          "Snapchat": "Snapchat",
          "Snapchat Username": "Snapchat Username",
          "WhatsApp Username": "WhatsApp Username",
          "Meetme": "Meetme",
          "Meetme Username": "Meetme Username",
          "Youtube": "Youtube",
          "YouTube Username": "YouTube Username",
          "Twitter": "Twitter",
          "Twitter Username": "Twitter Username",
          "TikTok Username": "TikTok Username",
          "Tumblr Username": "Tumblr Username",
          "BenefitPay": "BenefitPay",
          "Link url": "Link url",
          "Paypal": "Paypal",
          "Apple Music": "Apple Music",
          "Spotify": "Spotify",
          "SoundCloud": "SoundCloud",
          "Microsoft Teams": "Microsoft Teams",
          "Podcast": "Podcast",
          "Zoom Meeting": "Zoom Meeting",
          'Website': 'Website',
          'Play Store': 'Play Store',
          'Food Menu': 'Food Menu',
          'Google Review': 'Google Review',
          'Huawei App': 'Huawei App',
          'IOS App': 'IOS App',
          'Tripadvisor': 'Tripadvisor',
          'url': 'URL',
          'App Name Title': 'App Name Title',
          'App Name': 'App Name',
          'Application Name': 'Application Name',
          'Website url': 'Website URL',
          'Play Store url': 'Play Store URL',
          'Food Menu url': 'Food Menu URL',
          'Google Review url': 'Google Review URL',
          'Huawei App url': 'Huawei App URL',
          'IOS App url': 'IOS App URL',
          'Tripadvisor url': 'Tripadvisor URL',
          'Current Password': 'Current Password',
          'New Password': 'New Password',
          'Update Password': 'Update Password',
          'Deactivate Flick': 'Deactivate Flick',
          'this will make your profile hidden and your flick will not be accessible by anyone':
              'This will make your profile hidden, and your Flick will not be accessible by anyone',
          'Custom Message': 'Custom Message',
          'Add your Customer Message here': 'Add your Custom Message here',
          'Are you sure you want to Logout?':
              'Are you sure you want to Logout?',
          'Are you sure you want to Exit?': 'Are you sure you want to Exit?',
          'No': 'No',
          'Exit': 'Exit',
          'FAQ': 'FAQ ',
        },
      };
}
